/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vmeta.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "video-metadata/vmeta.pb-c.h"
void   vmeta__quaternion__init
                     (Vmeta__Quaternion         *message)
{
  static const Vmeta__Quaternion init_value = VMETA__QUATERNION__INIT;
  *message = init_value;
}
size_t vmeta__quaternion__get_packed_size
                     (const Vmeta__Quaternion *message)
{
  assert(message->base.descriptor == &vmeta__quaternion__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__quaternion__pack
                     (const Vmeta__Quaternion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__quaternion__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__quaternion__pack_to_buffer
                     (const Vmeta__Quaternion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__quaternion__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__Quaternion *
       vmeta__quaternion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__Quaternion *)
     protobuf_c_message_unpack (&vmeta__quaternion__descriptor,
                                allocator, len, data);
}
void   vmeta__quaternion__free_unpacked
                     (Vmeta__Quaternion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__quaternion__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__location__init
                     (Vmeta__Location         *message)
{
  static const Vmeta__Location init_value = VMETA__LOCATION__INIT;
  *message = init_value;
}
size_t vmeta__location__get_packed_size
                     (const Vmeta__Location *message)
{
  assert(message->base.descriptor == &vmeta__location__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__location__pack
                     (const Vmeta__Location *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__location__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__location__pack_to_buffer
                     (const Vmeta__Location *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__location__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__Location *
       vmeta__location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__Location *)
     protobuf_c_message_unpack (&vmeta__location__descriptor,
                                allocator, len, data);
}
void   vmeta__location__free_unpacked
                     (Vmeta__Location *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__location__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__vector3__init
                     (Vmeta__Vector3         *message)
{
  static const Vmeta__Vector3 init_value = VMETA__VECTOR3__INIT;
  *message = init_value;
}
size_t vmeta__vector3__get_packed_size
                     (const Vmeta__Vector3 *message)
{
  assert(message->base.descriptor == &vmeta__vector3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__vector3__pack
                     (const Vmeta__Vector3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__vector3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__vector3__pack_to_buffer
                     (const Vmeta__Vector3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__vector3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__Vector3 *
       vmeta__vector3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__Vector3 *)
     protobuf_c_message_unpack (&vmeta__vector3__descriptor,
                                allocator, len, data);
}
void   vmeta__vector3__free_unpacked
                     (Vmeta__Vector3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__vector3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__ned__init
                     (Vmeta__NED         *message)
{
  static const Vmeta__NED init_value = VMETA__NED__INIT;
  *message = init_value;
}
size_t vmeta__ned__get_packed_size
                     (const Vmeta__NED *message)
{
  assert(message->base.descriptor == &vmeta__ned__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__ned__pack
                     (const Vmeta__NED *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__ned__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__ned__pack_to_buffer
                     (const Vmeta__NED *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__ned__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__NED *
       vmeta__ned__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__NED *)
     protobuf_c_message_unpack (&vmeta__ned__descriptor,
                                allocator, len, data);
}
void   vmeta__ned__free_unpacked
                     (Vmeta__NED *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__ned__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__bounding_box__init
                     (Vmeta__BoundingBox         *message)
{
  static const Vmeta__BoundingBox init_value = VMETA__BOUNDING_BOX__INIT;
  *message = init_value;
}
size_t vmeta__bounding_box__get_packed_size
                     (const Vmeta__BoundingBox *message)
{
  assert(message->base.descriptor == &vmeta__bounding_box__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__bounding_box__pack
                     (const Vmeta__BoundingBox *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__bounding_box__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__bounding_box__pack_to_buffer
                     (const Vmeta__BoundingBox *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__bounding_box__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__BoundingBox *
       vmeta__bounding_box__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__BoundingBox *)
     protobuf_c_message_unpack (&vmeta__bounding_box__descriptor,
                                allocator, len, data);
}
void   vmeta__bounding_box__free_unpacked
                     (Vmeta__BoundingBox *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__bounding_box__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__drone_metadata__init
                     (Vmeta__DroneMetadata         *message)
{
  static const Vmeta__DroneMetadata init_value = VMETA__DRONE_METADATA__INIT;
  *message = init_value;
}
size_t vmeta__drone_metadata__get_packed_size
                     (const Vmeta__DroneMetadata *message)
{
  assert(message->base.descriptor == &vmeta__drone_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__drone_metadata__pack
                     (const Vmeta__DroneMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__drone_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__drone_metadata__pack_to_buffer
                     (const Vmeta__DroneMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__drone_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__DroneMetadata *
       vmeta__drone_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__DroneMetadata *)
     protobuf_c_message_unpack (&vmeta__drone_metadata__descriptor,
                                allocator, len, data);
}
void   vmeta__drone_metadata__free_unpacked
                     (Vmeta__DroneMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__drone_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__camera_metadata__init
                     (Vmeta__CameraMetadata         *message)
{
  static const Vmeta__CameraMetadata init_value = VMETA__CAMERA_METADATA__INIT;
  *message = init_value;
}
size_t vmeta__camera_metadata__get_packed_size
                     (const Vmeta__CameraMetadata *message)
{
  assert(message->base.descriptor == &vmeta__camera_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__camera_metadata__pack
                     (const Vmeta__CameraMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__camera_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__camera_metadata__pack_to_buffer
                     (const Vmeta__CameraMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__camera_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__CameraMetadata *
       vmeta__camera_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__CameraMetadata *)
     protobuf_c_message_unpack (&vmeta__camera_metadata__descriptor,
                                allocator, len, data);
}
void   vmeta__camera_metadata__free_unpacked
                     (Vmeta__CameraMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__camera_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__tracking_proposal_metadata__init
                     (Vmeta__TrackingProposalMetadata         *message)
{
  static const Vmeta__TrackingProposalMetadata init_value = VMETA__TRACKING_PROPOSAL_METADATA__INIT;
  *message = init_value;
}
size_t vmeta__tracking_proposal_metadata__get_packed_size
                     (const Vmeta__TrackingProposalMetadata *message)
{
  assert(message->base.descriptor == &vmeta__tracking_proposal_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__tracking_proposal_metadata__pack
                     (const Vmeta__TrackingProposalMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__tracking_proposal_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__tracking_proposal_metadata__pack_to_buffer
                     (const Vmeta__TrackingProposalMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__tracking_proposal_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__TrackingProposalMetadata *
       vmeta__tracking_proposal_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__TrackingProposalMetadata *)
     protobuf_c_message_unpack (&vmeta__tracking_proposal_metadata__descriptor,
                                allocator, len, data);
}
void   vmeta__tracking_proposal_metadata__free_unpacked
                     (Vmeta__TrackingProposalMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__tracking_proposal_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__tracking_metadata__init
                     (Vmeta__TrackingMetadata         *message)
{
  static const Vmeta__TrackingMetadata init_value = VMETA__TRACKING_METADATA__INIT;
  *message = init_value;
}
size_t vmeta__tracking_metadata__get_packed_size
                     (const Vmeta__TrackingMetadata *message)
{
  assert(message->base.descriptor == &vmeta__tracking_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__tracking_metadata__pack
                     (const Vmeta__TrackingMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__tracking_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__tracking_metadata__pack_to_buffer
                     (const Vmeta__TrackingMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__tracking_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__TrackingMetadata *
       vmeta__tracking_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__TrackingMetadata *)
     protobuf_c_message_unpack (&vmeta__tracking_metadata__descriptor,
                                allocator, len, data);
}
void   vmeta__tracking_metadata__free_unpacked
                     (Vmeta__TrackingMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__tracking_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__wifi_link_metadata__init
                     (Vmeta__WifiLinkMetadata         *message)
{
  static const Vmeta__WifiLinkMetadata init_value = VMETA__WIFI_LINK_METADATA__INIT;
  *message = init_value;
}
size_t vmeta__wifi_link_metadata__get_packed_size
                     (const Vmeta__WifiLinkMetadata *message)
{
  assert(message->base.descriptor == &vmeta__wifi_link_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__wifi_link_metadata__pack
                     (const Vmeta__WifiLinkMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__wifi_link_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__wifi_link_metadata__pack_to_buffer
                     (const Vmeta__WifiLinkMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__wifi_link_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__WifiLinkMetadata *
       vmeta__wifi_link_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__WifiLinkMetadata *)
     protobuf_c_message_unpack (&vmeta__wifi_link_metadata__descriptor,
                                allocator, len, data);
}
void   vmeta__wifi_link_metadata__free_unpacked
                     (Vmeta__WifiLinkMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__wifi_link_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__starfish_link_info__init
                     (Vmeta__StarfishLinkInfo         *message)
{
  static const Vmeta__StarfishLinkInfo init_value = VMETA__STARFISH_LINK_INFO__INIT;
  *message = init_value;
}
size_t vmeta__starfish_link_info__get_packed_size
                     (const Vmeta__StarfishLinkInfo *message)
{
  assert(message->base.descriptor == &vmeta__starfish_link_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__starfish_link_info__pack
                     (const Vmeta__StarfishLinkInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__starfish_link_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__starfish_link_info__pack_to_buffer
                     (const Vmeta__StarfishLinkInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__starfish_link_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__StarfishLinkInfo *
       vmeta__starfish_link_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__StarfishLinkInfo *)
     protobuf_c_message_unpack (&vmeta__starfish_link_info__descriptor,
                                allocator, len, data);
}
void   vmeta__starfish_link_info__free_unpacked
                     (Vmeta__StarfishLinkInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__starfish_link_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__starfish_link_metadata__init
                     (Vmeta__StarfishLinkMetadata         *message)
{
  static const Vmeta__StarfishLinkMetadata init_value = VMETA__STARFISH_LINK_METADATA__INIT;
  *message = init_value;
}
size_t vmeta__starfish_link_metadata__get_packed_size
                     (const Vmeta__StarfishLinkMetadata *message)
{
  assert(message->base.descriptor == &vmeta__starfish_link_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__starfish_link_metadata__pack
                     (const Vmeta__StarfishLinkMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__starfish_link_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__starfish_link_metadata__pack_to_buffer
                     (const Vmeta__StarfishLinkMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__starfish_link_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__StarfishLinkMetadata *
       vmeta__starfish_link_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__StarfishLinkMetadata *)
     protobuf_c_message_unpack (&vmeta__starfish_link_metadata__descriptor,
                                allocator, len, data);
}
void   vmeta__starfish_link_metadata__free_unpacked
                     (Vmeta__StarfishLinkMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__starfish_link_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__link_metadata__init
                     (Vmeta__LinkMetadata         *message)
{
  static const Vmeta__LinkMetadata init_value = VMETA__LINK_METADATA__INIT;
  *message = init_value;
}
size_t vmeta__link_metadata__get_packed_size
                     (const Vmeta__LinkMetadata *message)
{
  assert(message->base.descriptor == &vmeta__link_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__link_metadata__pack
                     (const Vmeta__LinkMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__link_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__link_metadata__pack_to_buffer
                     (const Vmeta__LinkMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__link_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__LinkMetadata *
       vmeta__link_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__LinkMetadata *)
     protobuf_c_message_unpack (&vmeta__link_metadata__descriptor,
                                allocator, len, data);
}
void   vmeta__link_metadata__free_unpacked
                     (Vmeta__LinkMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__link_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vmeta__timed_metadata__init
                     (Vmeta__TimedMetadata         *message)
{
  static const Vmeta__TimedMetadata init_value = VMETA__TIMED_METADATA__INIT;
  *message = init_value;
}
size_t vmeta__timed_metadata__get_packed_size
                     (const Vmeta__TimedMetadata *message)
{
  assert(message->base.descriptor == &vmeta__timed_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vmeta__timed_metadata__pack
                     (const Vmeta__TimedMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vmeta__timed_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vmeta__timed_metadata__pack_to_buffer
                     (const Vmeta__TimedMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vmeta__timed_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vmeta__TimedMetadata *
       vmeta__timed_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vmeta__TimedMetadata *)
     protobuf_c_message_unpack (&vmeta__timed_metadata__descriptor,
                                allocator, len, data);
}
void   vmeta__timed_metadata__free_unpacked
                     (Vmeta__TimedMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vmeta__timed_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor vmeta__quaternion__field_descriptors[4] =
{
  {
    "w",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Quaternion, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Quaternion, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Quaternion, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Quaternion, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__quaternion__field_indices_by_name[] = {
  0,   /* field[0] = w */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
  3,   /* field[3] = z */
};
static const ProtobufCIntRange vmeta__quaternion__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor vmeta__quaternion__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.Quaternion",
  "Quaternion",
  "Vmeta__Quaternion",
  "vmeta",
  sizeof(Vmeta__Quaternion),
  4,
  vmeta__quaternion__field_descriptors,
  vmeta__quaternion__field_indices_by_name,
  1,  vmeta__quaternion__number_ranges,
  (ProtobufCMessageInit) vmeta__quaternion__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__location__field_descriptors[6] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Location, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Location, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Location, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sv_count",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Location, sv_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "horizontal_accuracy",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Location, horizontal_accuracy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertical_accuracy",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Location, vertical_accuracy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__location__field_indices_by_name[] = {
  2,   /* field[2] = altitude */
  4,   /* field[4] = horizontal_accuracy */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
  3,   /* field[3] = sv_count */
  5,   /* field[5] = vertical_accuracy */
};
static const ProtobufCIntRange vmeta__location__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor vmeta__location__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.Location",
  "Location",
  "Vmeta__Location",
  "vmeta",
  sizeof(Vmeta__Location),
  6,
  vmeta__location__field_descriptors,
  vmeta__location__field_indices_by_name,
  1,  vmeta__location__number_ranges,
  (ProtobufCMessageInit) vmeta__location__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__vector3__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Vector3, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Vector3, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__Vector3, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__vector3__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange vmeta__vector3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vmeta__vector3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.Vector3",
  "Vector3",
  "Vmeta__Vector3",
  "vmeta",
  sizeof(Vmeta__Vector3),
  3,
  vmeta__vector3__field_descriptors,
  vmeta__vector3__field_indices_by_name,
  1,  vmeta__vector3__number_ranges,
  (ProtobufCMessageInit) vmeta__vector3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__ned__field_descriptors[3] =
{
  {
    "north",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__NED, north),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "east",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__NED, east),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "down",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__NED, down),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__ned__field_indices_by_name[] = {
  2,   /* field[2] = down */
  1,   /* field[1] = east */
  0,   /* field[0] = north */
};
static const ProtobufCIntRange vmeta__ned__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vmeta__ned__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.NED",
  "NED",
  "Vmeta__NED",
  "vmeta",
  sizeof(Vmeta__NED),
  3,
  vmeta__ned__field_descriptors,
  vmeta__ned__field_indices_by_name,
  1,  vmeta__ned__number_ranges,
  (ProtobufCMessageInit) vmeta__ned__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__bounding_box__field_descriptors[7] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__BoundingBox, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__BoundingBox, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__BoundingBox, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__BoundingBox, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_class",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vmeta__BoundingBox, object_class),
    &vmeta__tracking_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confidence",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__BoundingBox, confidence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__BoundingBox, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__bounding_box__field_indices_by_name[] = {
  5,   /* field[5] = confidence */
  3,   /* field[3] = height */
  4,   /* field[4] = object_class */
  6,   /* field[6] = uid */
  2,   /* field[2] = width */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange vmeta__bounding_box__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor vmeta__bounding_box__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.BoundingBox",
  "BoundingBox",
  "Vmeta__BoundingBox",
  "vmeta",
  sizeof(Vmeta__BoundingBox),
  7,
  vmeta__bounding_box__field_descriptors,
  vmeta__bounding_box__field_indices_by_name,
  1,  vmeta__bounding_box__number_ranges,
  (ProtobufCMessageInit) vmeta__bounding_box__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__drone_metadata__field_descriptors[8] =
{
  {
    "quat",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__DroneMetadata, quat),
    &vmeta__quaternion__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__DroneMetadata, location),
    &vmeta__location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ground_distance",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__DroneMetadata, ground_distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__DroneMetadata, speed),
    &vmeta__ned__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_percentage",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__DroneMetadata, battery_percentage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flying_state",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vmeta__DroneMetadata, flying_state),
    &vmeta__flying_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__DroneMetadata, position),
    &vmeta__ned__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local_position",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__DroneMetadata, local_position),
    &vmeta__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__drone_metadata__field_indices_by_name[] = {
  4,   /* field[4] = battery_percentage */
  5,   /* field[5] = flying_state */
  2,   /* field[2] = ground_distance */
  7,   /* field[7] = local_position */
  1,   /* field[1] = location */
  6,   /* field[6] = position */
  0,   /* field[0] = quat */
  3,   /* field[3] = speed */
};
static const ProtobufCIntRange vmeta__drone_metadata__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 7, 5 },
  { 9, 6 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor vmeta__drone_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.DroneMetadata",
  "DroneMetadata",
  "Vmeta__DroneMetadata",
  "vmeta",
  sizeof(Vmeta__DroneMetadata),
  8,
  vmeta__drone_metadata__field_descriptors,
  vmeta__drone_metadata__field_indices_by_name,
  3,  vmeta__drone_metadata__number_ranges,
  (ProtobufCMessageInit) vmeta__drone_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__camera_metadata__field_descriptors[11] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_quat",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, base_quat),
    &vmeta__quaternion__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quat",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, quat),
    &vmeta__quaternion__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exposure_time",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, exposure_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iso_gain",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, iso_gain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "awb_r_gain",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, awb_r_gain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "awb_b_gain",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, awb_b_gain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hfov",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, hfov),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vfov",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, vfov),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "utc_timestamp",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, utc_timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "utc_timestamp_accuracy",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__CameraMetadata, utc_timestamp_accuracy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__camera_metadata__field_indices_by_name[] = {
  6,   /* field[6] = awb_b_gain */
  5,   /* field[5] = awb_r_gain */
  1,   /* field[1] = base_quat */
  3,   /* field[3] = exposure_time */
  7,   /* field[7] = hfov */
  4,   /* field[4] = iso_gain */
  2,   /* field[2] = quat */
  0,   /* field[0] = timestamp */
  9,   /* field[9] = utc_timestamp */
  10,   /* field[10] = utc_timestamp_accuracy */
  8,   /* field[8] = vfov */
};
static const ProtobufCIntRange vmeta__camera_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor vmeta__camera_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.CameraMetadata",
  "CameraMetadata",
  "Vmeta__CameraMetadata",
  "vmeta",
  sizeof(Vmeta__CameraMetadata),
  11,
  vmeta__camera_metadata__field_descriptors,
  vmeta__camera_metadata__field_indices_by_name,
  1,  vmeta__camera_metadata__number_ranges,
  (ProtobufCMessageInit) vmeta__camera_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__tracking_proposal_metadata__field_descriptors[2] =
{
  {
    "proposals",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vmeta__TrackingProposalMetadata, n_proposals),
    offsetof(Vmeta__TrackingProposalMetadata, proposals),
    &vmeta__bounding_box__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TrackingProposalMetadata, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__tracking_proposal_metadata__field_indices_by_name[] = {
  0,   /* field[0] = proposals */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange vmeta__tracking_proposal_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vmeta__tracking_proposal_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.TrackingProposalMetadata",
  "TrackingProposalMetadata",
  "Vmeta__TrackingProposalMetadata",
  "vmeta",
  sizeof(Vmeta__TrackingProposalMetadata),
  2,
  vmeta__tracking_proposal_metadata__field_descriptors,
  vmeta__tracking_proposal_metadata__field_indices_by_name,
  1,  vmeta__tracking_proposal_metadata__number_ranges,
  (ProtobufCMessageInit) vmeta__tracking_proposal_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__tracking_metadata__field_descriptors[5] =
{
  {
    "target",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TrackingMetadata, target),
    &vmeta__bounding_box__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TrackingMetadata, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TrackingMetadata, quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TrackingMetadata, state),
    &vmeta__tracking_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cookie",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TrackingMetadata, cookie),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__tracking_metadata__field_indices_by_name[] = {
  4,   /* field[4] = cookie */
  2,   /* field[2] = quality */
  3,   /* field[3] = state */
  0,   /* field[0] = target */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange vmeta__tracking_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor vmeta__tracking_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.TrackingMetadata",
  "TrackingMetadata",
  "Vmeta__TrackingMetadata",
  "vmeta",
  sizeof(Vmeta__TrackingMetadata),
  5,
  vmeta__tracking_metadata__field_descriptors,
  vmeta__tracking_metadata__field_indices_by_name,
  1,  vmeta__tracking_metadata__number_ranges,
  (ProtobufCMessageInit) vmeta__tracking_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__wifi_link_metadata__field_descriptors[3] =
{
  {
    "goodput",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__WifiLinkMetadata, goodput),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__WifiLinkMetadata, quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__WifiLinkMetadata, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__wifi_link_metadata__field_indices_by_name[] = {
  0,   /* field[0] = goodput */
  1,   /* field[1] = quality */
  2,   /* field[2] = rssi */
};
static const ProtobufCIntRange vmeta__wifi_link_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vmeta__wifi_link_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.WifiLinkMetadata",
  "WifiLinkMetadata",
  "Vmeta__WifiLinkMetadata",
  "vmeta",
  sizeof(Vmeta__WifiLinkMetadata),
  3,
  vmeta__wifi_link_metadata__field_descriptors,
  vmeta__wifi_link_metadata__field_indices_by_name,
  1,  vmeta__wifi_link_metadata__number_ranges,
  (ProtobufCMessageInit) vmeta__wifi_link_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__starfish_link_info__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vmeta__StarfishLinkInfo, type),
    &vmeta__link_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vmeta__StarfishLinkInfo, status),
    &vmeta__link_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__StarfishLinkInfo, quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "active",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Vmeta__StarfishLinkInfo, active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__starfish_link_info__field_indices_by_name[] = {
  3,   /* field[3] = active */
  2,   /* field[2] = quality */
  1,   /* field[1] = status */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange vmeta__starfish_link_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor vmeta__starfish_link_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.StarfishLinkInfo",
  "StarfishLinkInfo",
  "Vmeta__StarfishLinkInfo",
  "vmeta",
  sizeof(Vmeta__StarfishLinkInfo),
  4,
  vmeta__starfish_link_info__field_descriptors,
  vmeta__starfish_link_info__field_indices_by_name,
  1,  vmeta__starfish_link_info__number_ranges,
  (ProtobufCMessageInit) vmeta__starfish_link_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__starfish_link_metadata__field_descriptors[2] =
{
  {
    "links",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vmeta__StarfishLinkMetadata, n_links),
    offsetof(Vmeta__StarfishLinkMetadata, links),
    &vmeta__starfish_link_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vmeta__StarfishLinkMetadata, quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__starfish_link_metadata__field_indices_by_name[] = {
  0,   /* field[0] = links */
  1,   /* field[1] = quality */
};
static const ProtobufCIntRange vmeta__starfish_link_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vmeta__starfish_link_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.StarfishLinkMetadata",
  "StarfishLinkMetadata",
  "Vmeta__StarfishLinkMetadata",
  "vmeta",
  sizeof(Vmeta__StarfishLinkMetadata),
  2,
  vmeta__starfish_link_metadata__field_descriptors,
  vmeta__starfish_link_metadata__field_indices_by_name,
  1,  vmeta__starfish_link_metadata__number_ranges,
  (ProtobufCMessageInit) vmeta__starfish_link_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__link_metadata__field_descriptors[2] =
{
  {
    "wifi",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vmeta__LinkMetadata, protocol_case),
    offsetof(Vmeta__LinkMetadata, wifi),
    &vmeta__wifi_link_metadata__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "starfish",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vmeta__LinkMetadata, protocol_case),
    offsetof(Vmeta__LinkMetadata, starfish),
    &vmeta__starfish_link_metadata__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__link_metadata__field_indices_by_name[] = {
  1,   /* field[1] = starfish */
  0,   /* field[0] = wifi */
};
static const ProtobufCIntRange vmeta__link_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vmeta__link_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.LinkMetadata",
  "LinkMetadata",
  "Vmeta__LinkMetadata",
  "vmeta",
  sizeof(Vmeta__LinkMetadata),
  2,
  vmeta__link_metadata__field_descriptors,
  vmeta__link_metadata__field_indices_by_name,
  1,  vmeta__link_metadata__number_ranges,
  (ProtobufCMessageInit) vmeta__link_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vmeta__timed_metadata__field_descriptors[5] =
{
  {
    "drone",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TimedMetadata, drone),
    &vmeta__drone_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TimedMetadata, camera),
    &vmeta__camera_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "links",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vmeta__TimedMetadata, n_links),
    offsetof(Vmeta__TimedMetadata, links),
    &vmeta__link_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tracking",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TimedMetadata, tracking),
    &vmeta__tracking_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proposal",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vmeta__TimedMetadata, proposal),
    &vmeta__tracking_proposal_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vmeta__timed_metadata__field_indices_by_name[] = {
  1,   /* field[1] = camera */
  0,   /* field[0] = drone */
  2,   /* field[2] = links */
  4,   /* field[4] = proposal */
  3,   /* field[3] = tracking */
};
static const ProtobufCIntRange vmeta__timed_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor vmeta__timed_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vmeta.TimedMetadata",
  "TimedMetadata",
  "Vmeta__TimedMetadata",
  "vmeta",
  sizeof(Vmeta__TimedMetadata),
  5,
  vmeta__timed_metadata__field_descriptors,
  vmeta__timed_metadata__field_indices_by_name,
  1,  vmeta__timed_metadata__number_ranges,
  (ProtobufCMessageInit) vmeta__timed_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue vmeta__tracking_class__enum_values_by_number[8] =
{
  { "TC_PERSON", "VMETA__TRACKING_CLASS__TC_PERSON", 0 },
  { "TC_ANIMAL", "VMETA__TRACKING_CLASS__TC_ANIMAL", 1 },
  { "TC_BICYCLE", "VMETA__TRACKING_CLASS__TC_BICYCLE", 2 },
  { "TC_BOAT", "VMETA__TRACKING_CLASS__TC_BOAT", 3 },
  { "TC_CAR", "VMETA__TRACKING_CLASS__TC_CAR", 4 },
  { "TC_HORSE", "VMETA__TRACKING_CLASS__TC_HORSE", 5 },
  { "TC_MOTORBIKE", "VMETA__TRACKING_CLASS__TC_MOTORBIKE", 6 },
  { "TC_UNDEFINED", "VMETA__TRACKING_CLASS__TC_UNDEFINED", 127 },
};
static const ProtobufCIntRange vmeta__tracking_class__value_ranges[] = {
{0, 0},{127, 7},{0, 8}
};
static const ProtobufCEnumValueIndex vmeta__tracking_class__enum_values_by_name[8] =
{
  { "TC_ANIMAL", 1 },
  { "TC_BICYCLE", 2 },
  { "TC_BOAT", 3 },
  { "TC_CAR", 4 },
  { "TC_HORSE", 5 },
  { "TC_MOTORBIKE", 6 },
  { "TC_PERSON", 0 },
  { "TC_UNDEFINED", 7 },
};
const ProtobufCEnumDescriptor vmeta__tracking_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vmeta.TrackingClass",
  "TrackingClass",
  "Vmeta__TrackingClass",
  "vmeta",
  8,
  vmeta__tracking_class__enum_values_by_number,
  8,
  vmeta__tracking_class__enum_values_by_name,
  2,
  vmeta__tracking_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue vmeta__tracking_state__enum_values_by_number[2] =
{
  { "TS_TRACKING", "VMETA__TRACKING_STATE__TS_TRACKING", 0 },
  { "TS_SEARCHING", "VMETA__TRACKING_STATE__TS_SEARCHING", 1 },
};
static const ProtobufCIntRange vmeta__tracking_state__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex vmeta__tracking_state__enum_values_by_name[2] =
{
  { "TS_SEARCHING", 1 },
  { "TS_TRACKING", 0 },
};
const ProtobufCEnumDescriptor vmeta__tracking_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vmeta.TrackingState",
  "TrackingState",
  "Vmeta__TrackingState",
  "vmeta",
  2,
  vmeta__tracking_state__enum_values_by_number,
  2,
  vmeta__tracking_state__enum_values_by_name,
  1,
  vmeta__tracking_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue vmeta__flying_state__enum_values_by_number[6] =
{
  { "FS_LANDED", "VMETA__FLYING_STATE__FS_LANDED", 0 },
  { "FS_TAKINGOFF", "VMETA__FLYING_STATE__FS_TAKINGOFF", 1 },
  { "FS_HOVERING", "VMETA__FLYING_STATE__FS_HOVERING", 2 },
  { "FS_FLYING", "VMETA__FLYING_STATE__FS_FLYING", 3 },
  { "FS_LANDING", "VMETA__FLYING_STATE__FS_LANDING", 4 },
  { "FS_EMERGENCY", "VMETA__FLYING_STATE__FS_EMERGENCY", 5 },
};
static const ProtobufCIntRange vmeta__flying_state__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex vmeta__flying_state__enum_values_by_name[6] =
{
  { "FS_EMERGENCY", 5 },
  { "FS_FLYING", 3 },
  { "FS_HOVERING", 2 },
  { "FS_LANDED", 0 },
  { "FS_LANDING", 4 },
  { "FS_TAKINGOFF", 1 },
};
const ProtobufCEnumDescriptor vmeta__flying_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vmeta.FlyingState",
  "FlyingState",
  "Vmeta__FlyingState",
  "vmeta",
  6,
  vmeta__flying_state__enum_values_by_number,
  6,
  vmeta__flying_state__enum_values_by_name,
  1,
  vmeta__flying_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue vmeta__link_type__enum_values_by_number[5] =
{
  { "LINK_TYPE_UNKNOWN", "VMETA__LINK_TYPE__LINK_TYPE_UNKNOWN", 0 },
  { "LINK_TYPE_LO", "VMETA__LINK_TYPE__LINK_TYPE_LO", 1 },
  { "LINK_TYPE_LAN", "VMETA__LINK_TYPE__LINK_TYPE_LAN", 2 },
  { "LINK_TYPE_WLAN", "VMETA__LINK_TYPE__LINK_TYPE_WLAN", 3 },
  { "LINK_TYPE_CELLULAR", "VMETA__LINK_TYPE__LINK_TYPE_CELLULAR", 4 },
};
static const ProtobufCIntRange vmeta__link_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex vmeta__link_type__enum_values_by_name[5] =
{
  { "LINK_TYPE_CELLULAR", 4 },
  { "LINK_TYPE_LAN", 2 },
  { "LINK_TYPE_LO", 1 },
  { "LINK_TYPE_UNKNOWN", 0 },
  { "LINK_TYPE_WLAN", 3 },
};
const ProtobufCEnumDescriptor vmeta__link_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vmeta.LinkType",
  "LinkType",
  "Vmeta__LinkType",
  "vmeta",
  5,
  vmeta__link_type__enum_values_by_number,
  5,
  vmeta__link_type__enum_values_by_name,
  1,
  vmeta__link_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue vmeta__link_status__enum_values_by_number[6] =
{
  { "LINK_STATUS_DOWN", "VMETA__LINK_STATUS__LINK_STATUS_DOWN", 0 },
  { "LINK_STATUS_UP", "VMETA__LINK_STATUS__LINK_STATUS_UP", 1 },
  { "LINK_STATUS_RUNNING", "VMETA__LINK_STATUS__LINK_STATUS_RUNNING", 2 },
  { "LINK_STATUS_READY", "VMETA__LINK_STATUS__LINK_STATUS_READY", 3 },
  { "LINK_STATUS_CONNECTING", "VMETA__LINK_STATUS__LINK_STATUS_CONNECTING", 4 },
  { "LINK_STATUS_ERROR", "VMETA__LINK_STATUS__LINK_STATUS_ERROR", 5 },
};
static const ProtobufCIntRange vmeta__link_status__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex vmeta__link_status__enum_values_by_name[6] =
{
  { "LINK_STATUS_CONNECTING", 4 },
  { "LINK_STATUS_DOWN", 0 },
  { "LINK_STATUS_ERROR", 5 },
  { "LINK_STATUS_READY", 3 },
  { "LINK_STATUS_RUNNING", 2 },
  { "LINK_STATUS_UP", 1 },
};
const ProtobufCEnumDescriptor vmeta__link_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vmeta.LinkStatus",
  "LinkStatus",
  "Vmeta__LinkStatus",
  "vmeta",
  6,
  vmeta__link_status__enum_values_by_number,
  6,
  vmeta__link_status__enum_values_by_name,
  1,
  vmeta__link_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
